name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          
          echo "## Model metrics" > report1.md
          cat metrics.txt >> report1.md

          echo "## Data viz" >> report1.md
          cml-publish feature_importance.png --md >> report1.md
          cml-publish residuals.png --md >> report1.md
          
          cml-send-comment report1.md